---
hostname: sulu.local
username: vagrant
userhome: /home/vagrant
usergroup: vagrant
document_root: /home/vagrant/share/web
deploy_dir: /home/vagrant/deploy
zsh_plugin: "git"
git_username: "sulu"
git_usermail: "sulu@sulu.local"
